ManageIQ/manageiq-providers-hawkular

.rubocop_local.yml

Fixes:
```
$ rubocop -d app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb 
For /home/bdunne/projects/redhat/manageiq-providers-openstack: configuration from /home/bdunne/projects/redhat/manageiq-providers-openstack/.rubocop.yml
configuration from /home/bdunne/projects/redhat/manageiq-providers-openstack/.rubocop-https---raw-githubusercontent-com-ManageIQ-guides-master--rubocop-base-yml
Default configuration from /home/bdunne/.gem/ruby/2.3.3/gems/rubocop-0.47.1/config/default.yml
Inheriting configuration from /home/bdunne/.gem/ruby/2.3.3/gems/rubocop-0.47.1/config/enabled.yml
Inheriting configuration from /home/bdunne/.gem/ruby/2.3.3/gems/rubocop-0.47.1/config/disabled.yml
Inheriting configuration from /home/bdunne/projects/redhat/manageiq-providers-openstack/.rub …
```

Add loggers to allowed global variables

---

app/models/manageiq/providers/hawkular/middleware_manager/middleware_server.rb
spec/models/manageiq/providers/hawkular/middleware_manager/middleware_server_spec.rb

This is a follow-up of those PRs, and can be merged independently (but the behaviour will only be enabled correctly when all three of them are merged):
https://github.com/ManageIQ/manageiq/pull/14565
https://github.com/ManageIQ/manageiq-ui-classic/pull/839

Add attributes to mark servers as (im)mutable

---

app/models/manageiq/providers/hawkular/common/event_catcher/stream_mixin.rb
app/models/manageiq/providers/hawkular/datawarehouse_manager/event_catcher/runner.rb
app/models/manageiq/providers/hawkular/datawarehouse_manager/event_catcher/stream.rb
spec/models/manageiq/providers/hawkular/datawarehouse_manager/event_catcher/stream_spec.rb
spec/vcr_cassettes/manageiq/providers/hawkular/datawarehouse_manager/event_catcher/stream.yml

Retrieve resolved alerts from hawkular.
To see the type of hawkular alerts we plan to use with this see [this](https://github.com/moolitayer/hawkular-curl-examples/tree/4a22cbc4bf6e7f1ae7ae0e617eb730247c7d19aa/ops-example)
Moved from https://github.com/ManageIQ/manageiq/pull/14299

Datawarehouse: Retrieve resolved alerts from hawkular

---

app/models/manageiq/providers/hawkular/inventory/collector/middleware_manager.rb
app/models/manageiq/providers/hawkular/inventory/parser/middleware_manager.rb
app/models/manageiq/providers/hawkular/middleware_manager/middleware_deployment.rb
spec/models/manageiq/providers/hawkular/inventory/parser/middleware_manager_spec.rb
spec/models/manageiq/providers/hawkular/middleware_manager/refresher_spec.rb
spec/vcr_cassettes/manageiq/providers/hawkular/middleware_manager/refresher.yml

Server status was being fetched from inventory's data resulting in wrong
reported status when server is down. Now, server status is resolved with
a combination of server's availability metric and its inventory status.
https://bugzilla.redhat.com/show_bug.cgi?id=1438816
This PR goes together with manageiq/manageiq-ui-classic#987. Merge order is not important and is not required to merge simultaneously.

Resolve middleware server status from availability metric

---

app/models/manageiq/providers/hawkular/inventory/parser/middleware_manager.rb
app/models/manageiq/providers/hawkular/middleware_manager/middleware_deployment.rb
spec/models/manageiq/providers/hawkular/middleware_manager/hawkular_helper.rb
spec/models/manageiq/providers/hawkular/middleware_manager/refresher_spec.rb
spec/vcr_cassettes/manageiq/providers/hawkular/middleware_manager/middleware_datasource.yml
spec/vcr_cassettes/manageiq/providers/hawkular/middleware_manager/middleware_messaging.yml
spec/vcr_cassettes/manageiq/providers/hawkular/middleware_manager/middleware_server.yml
spec/vcr_cassettes/manageiq/providers/hawkular/middleware_manager/refresher.yml
spec/vcr_cassettes/manageiq/providers/hawkular/middleware_manager/refresher_without_os.yml

Hawkular's inventory is being rewritten to store its inventory as metrics. The [hawkular-client-ruby](https://github.com/hawkular/hawkular-client-ruby) is being modified to make the inventory's change as transparent as possible for users of the ruby client, but this is not fully possible. This PR deals with changes required in MiQ side to work correctly with new's Hawkular inventory.
~~Note: This PR was worked on top of code changes of #6. To view the relevant differences, look only at the last commit.~~ #6 has been merged. Now, it this is rebased from master.
https://bugzilla.redhat.com/show_bug.cgi?id=1446286

Adaptations to have a working refresh for Hawkular's Inventory.next

---

app/models/manageiq/providers/hawkular/middleware_manager/live_metrics_capture.rb

Hawkular returns with an error status code if an empty list of metrics
is sent in the query. Indeed, it doesn't make sense to query the
hawkular server if no metrics were requested and, instead, an empty
object can be returned.
One use case where this method is used, is when generating performance
reports for middleware servers. If there is one server that has never been
in running state or has been down for a "long" time, it may not have any
metrics (all them may have expired and purged). If this happens, the
"metrics" argument of collect_stats_metrics will be empty.
https://bugzilla.redhat.com/show_bug.cgi?id=1445702

Don't attempt to query Hawkular if no metrics were provided

---

spec/models/manageiq/providers/hawkular/inventory/parser/middleware_manager_spec.rb

For testing, doubles are more than sufficient, especially if we can
remove all usages of RecursiveOpenStruct for this repository.
Needed for https://github.com/ManageIQ/manageiq/pull/15096
It's not to say that RecursiveOpenStruct should be removed everywhere, but where we can replace the only usage of it with simpler options, it's best to remove extra dependencies.

RecursiveOpenStruct isn't needed here or anywhere in this repo

---

.rspec
.rspec_ci
lib/tasks_private/spec.rake

This makes `bundle exec rspec spec` works as specified, and makes
startup of `rake spec` a little tiny bit faster.

Exclude ManageIQ specs from RSpec

---

app/models/manageiq/providers/hawkular/inventory/availability_updates.rb
app/models/manageiq/providers/hawkular/inventory/collector/availability_updates.rb
app/models/manageiq/providers/hawkular/inventory/parser/availability_updates.rb
app/models/manageiq/providers/hawkular/inventory/parser/middleware_manager.rb
app/models/manageiq/providers/hawkular/inventory/persister/availability_updates.rb
app/models/manageiq/providers/hawkular/middleware_manager/event_catcher/runner.rb
app/models/manageiq/providers/hawkular/middleware_manager/event_catcher/stream.rb
app/models/manageiq/providers/hawkular/middleware_manager/middleware_deployment.rb
app/models/manageiq/providers/hawkular/middleware_manager/middleware_server.rb
app/models/manageiq/providers/hawkular/middleware_manager/refresher.rb
spec/contexts/targeted_avail_updates.rb
spec/models/manageiq/providers/hawkular/inventory/parser/availability_updates_spec.rb
spec/models/manageiq/providers/hawkular/inventory/parser/middleware_manager_spec.rb
spec/models/manageiq/providers/hawkular/inventory/persister/availability_updates_spec.rb
spec/models/manageiq/providers/hawkular/middleware_manager/event_catcher/stream_spec.rb
spec/models/manageiq/providers/hawkular/middleware_manager/refresher_spec.rb
spec/spec_helper.rb

* A targeted refresh is added.
* This targeted refresh only updates the status field of deployment entities when an availability update is received by the refresh worker.
* Targeted refresh also updates server entities with the fetched new status.
* No other field is updated, nor entity creation or deletion is performed. That work is left to the full graph refresh.
* Event catcher is extended to retrieve availability metrics from Hawkular for all deployments in inventory. Availabilities are "parsed" and compared against the status stored in MiQ database. Deployments whose status has changed are enqueued to be updated in the refresh worker.
* Event catcher is extended to fetch availability metrics of each inventoried server in MiQ. Also, its server state is fetched from Hawkular's …

Extending event catcher and adding targeted refresh for availabilities

---

app/models/manageiq/providers/hawkular/middleware_manager.rb
app/models/manageiq/providers/hawkular/middleware_manager/alert_manager.rb
app/models/manageiq/providers/hawkular/middleware_manager/alert_profile_manager.rb
spec/factories/miq_alert.rb
spec/factories/miq_alert_set.rb
spec/integration/alert_mgmt_flows_spec.rb
spec/models/manageiq/providers/hawkular/inventory/parser/middleware_manager_spec.rb
spec/models/manageiq/providers/hawkular/middleware_manager/alert_profile_manager_spec.rb
spec/models/manageiq/providers/hawkular/middleware_manager/hawkular_helper.rb
spec/models/manageiq/providers/hawkular/middleware_manager_spec.rb
spec/vcr_cassettes/integration/alert_mgmt_flows/add_alerts_to_profile_with_no_servers.yml
spec/vcr_cassettes/integration/alert_mgmt_flows/add_servers_to_profile_with_no_alerts.yml
spec/vcr_cassettes/integration/alert_mgmt_flows/alerts_crud_flow.yml
spec/vcr_cassettes/integration/alert_mgmt_flows/assign_unassign_alert_to_profile_with_servers.yml
spec/vcr_cassettes/integration/alert_mgmt_flows/assign_unassign_server_to_profile_with_alerts.yml
spec/vcr_cassettes/integration/alert_mgmt_flows/fallback_to_old_ids_format.yml
spec/vcr_cassettes/integration/alert_mgmt_flows/profiles_hawkular_cleanup.yml
spec/vcr_cassettes/integration/alert_mgmt_flows/profiles_hawkular_setup.yml

This is a border case. Issue is discussed in ManageIQ/manageiq#10674.
@miq-bot add_label enhancement, alerts

Avoid trigger id collisions when Hawkular is linked to multiple MiQ installations

---

app/models/manageiq/providers/hawkular/datawarehouse_manager.rb
app/models/manageiq/providers/hawkular/middleware_manager.rb
manageiq-providers-hawkular.gemspec

Depends on https://github.com/hawkular/hawkular-client-ruby/pull/222,
which adds new names for the errors on Hawkular ruby client.

Client error name format unification

---

app/models/manageiq/providers/hawkular/middleware_manager.rb

Because of:
* https://github.com/ManageIQ/manageiq-schema/pull/49
* https://github.com/ManageIQ/manageiq/pull/15315
Usage of `alert[:expression]` no longer works. Changing everything to use method/attribute accessors.

Changing bracket syntax for method/attribute syntax in update_alerts

---

app/models/manageiq/providers/hawkular/inventory/collector/middleware_manager.rb
app/models/manageiq/providers/hawkular/inventory/parser/middleware_manager.rb
spec/models/manageiq/providers/hawkular/inventory/parser/middleware_manager_spec.rb

Fixes issue #35. VMs and MW servers are not being cross-linked because
Hawkular Agent is reporting Machine ID as a 32 character string - a GUID
withouth dashes -, while RHVM provider is reporting machine ids as 36
character strings - GUID with dashes in standard locations.
This patch is adding dashes at standard locations to machine id reported
by Hawkular Agent, if needed.
Also, collector should not escape feed id when retrieving OS resource
types. This was preventing cross-linking to happen for MW servers in
domain mode.

Fixes VMs and MW servers not being cross-linked when GUIDs differ only because of dashes

---

app/models/manageiq/providers/hawkular/inventory/parser/middleware_manager.rb
app/models/manageiq/providers/hawkular/middleware_manager/alert_profile_manager.rb
app/models/manageiq/providers/hawkular/middleware_manager/event_catcher/runner.rb
spec/models/manageiq/providers/hawkular/inventory/parser/middleware_manager_spec.rb
spec/models/manageiq/providers/hawkular/middleware_manager/alert_profile_manager_spec.rb

* Event catcher was testing the wrong type and events weren't being passed to miq core for handling.
* alternate_machine_id method was assuming that the recevied machine id was 32 characters length and failing when this was not the case.
* Feed id was being escaped when adding members to Hawkular alert profiles and linking the alert to the wrong metrics in some cases. Escaping is removed because isn't needed as noted in https://github.com/ManageIQ/manageiq/issues/15756#issuecomment-324452842
Event handling issue: ManageIQ/manageiq#15756

Fixes event handling and generation of alternate machine in parser

---

GETTING_STARTED.md

In the getting Started md is missed the "install" in the dnf command.

Missed  "install" in dnf command in system dependencies installation

---

app/models/manageiq/providers/hawkular/middleware_manager/alert_manager.rb

This is required by ManageIQ/manageiq#16125 and ManageIQ/manageiq#16113 to generate the conditions.
cc @josejulio 
https://issues.jboss.org/browse/HAWKULAR-1255

Add support to Datasource and Web Sessions conditions

---

app/models/manageiq/providers/hawkular/middleware_manager.rb
config/settings.yml
spec/models/manageiq/providers/hawkular/middleware_manager_spec.rb

When server or domain operation is done, an event in the timeline
is logged. Either if the operation succeds of fails.
Jira: https://issues.jboss.org/browse/HAWKULAR-1249
Must be merged first: ManageIQ/manageiq-schema#86

Support for timeline events for MW Server and MW domain power operations

---

GETTING_STARTED.md

Running with Ruby 2.3.0 gives this error:
There was an error parsing `Gemfile`: Ruby versions less than 2.3.1 are unsupported!. Bundler cannot continue.

Fix min Ruby to be 2.3.1 per the recent core change, otherwise it fails

---

spec/models/manageiq/providers/hawkular/middleware_manager/refresher_spec.rb

Fix the following warning on some specs:
```
WARNING: Use of `have_attributes` with array access (:[]) is deprecated and will be removed shortly.
If you're matching attributes in hashes, use appropriate hash matchers instead (`include`, `eq`).
Called from (..):59:in `assert_specific_datasource'
```
/cc @abonas

Fix warnings on specs

---

app/models/manageiq/providers/hawkular/inventory/parser/middleware_manager.rb
app/models/manageiq/providers/hawkular/middleware_manager/middleware_server_eap.rb
app/models/manageiq/providers/hawkular/middleware_manager/middleware_server_wildfly.rb

Sub-classing MiddlewareServer into more specific classes for Wildfly and EAP
Depends on: https://github.com/ManageIQ/manageiq-schema/pull/81
Depends on: https://github.com/ManageIQ/manageiq/pull/16126
Resolves: https://issues.jboss.org/browse/HAWKULAR-1248

Migrate MiddlewareServer to MiddlewareServerWildfly and MiddlewareServerEap

---

app/models/manageiq/providers/hawkular/middleware_manager.rb

Per this comment[1], it has been moved to MiddlewareDiagnosticReport model, so we can remove it safely.
[1]: https://github.com/ManageIQ/manageiq-providers-hawkular/pull/9#discussion_r146354161

Remove JDR operation from MiddlewareManager

---

app/models/manageiq/providers/hawkular/middleware_manager/middleware_diagnostic_report.rb

As stated in PR for core repo, we have to use different base class otherwise we are unable to fully use report data and display data in table with pagination, sort and such.
While changing the base class I also altered the class MiddlewareDiagnosticReport not to include table name and belongs to, which should be part of core functionality.

Use base class MiddlewareDiagnosticReport so we can fully use report to display data

---

spec/models/manageiq/providers/hawkular/middleware_manager/middleware_server_spec.rb

It is fixed a typo on a live metric name: mw_aggregated_servlet_time
Here is the fix on the core repo: https://github.com/ManageIQ/manageiq/pull/16363
@abonas who should I ping to review this? 
And how this dependency with core repo is handled? It needs some sync with core.

Typo fixed on Live metrics name: mw_aggregated_servlet_time

---

app/models/manageiq/providers/hawkular/middleware_manager/alert_manager.rb
spec/models/manageiq/providers/hawkular/middleware_manager/alert_manager_spec.rb

When alerts type Datasource and Mesagging are create in hawkular conditions and dataID is nil, the problem is getting the livemetrics of these kinds of alerts.
Fix Alerts of https://bugzilla.redhat.com/show_bug.cgi?id=1505343

Fix problem getting live metrics when trigger is created with Datasource and Mesagging types (bugzilla 1505343)

---

app/models/manageiq/providers/hawkular/middleware_manager/middleware_server.rb

Overriding `supported_models` let us tell to whole MiddlewareServer inheritance that their metrics are listed in the same metrics yaml: [product/live_metrics/middleware_server.yml](https://github.com/ManageIQ/manageiq/blob/master/product/live_metrics/middleware_server.yaml).
Since right now there aren't differences - regarding to live metrics - between EAP/Wildfly there is no need to split file into 3 different ones. When new metrics introduces for only one of the middleware servers kinds, then would be time to split it.

[1511961] Middleware server reports fixed after introducing STI on MiddlewareServer

---

app/models/manageiq/providers/hawkular/middleware_manager.rb

Re-add remove datasource operation missing since https://github.com/ManageIQ/manageiq-providers-hawkular/pull/9.
Fixes: [BUG 1515285](https://bugzilla.redhat.com/show_bug.cgi?id=1515285)
I'm not sure though if this is the correct approach, or I should use a separate method in `app/models/manageiq/providers/hawkular/inventory/server_operations.rb` instead. This solution is not firing any error when run multiple times and basically in any case when the result is an error event...
@cfcosta, please review

Re-add remove datasource operation

---

app/models/manageiq/providers/hawkular/middleware_manager/middleware_server.rb

This PR is a solution for the following BZ bug
https://bugzilla.redhat.com/show_bug.cgi?id=1514124
As well, it is related to the following PR already merged: https://github.com/ManageIQ/manageiq-providers-hawkular/pull/106
The introduction of the STI for MiddlewareServer broke charts and reports up for all MW Servers. It happened because it broke a convention between class name and metrics description file. Files are named like `_middleware_server.yaml` but now, with the STI is looking for `_middleware_server_eap.yaml` and `_middleware_server_wildfly.yaml`
With this PR is also fixing Chart render problems introduced by the STI.
STI was introduced in #60

Fixing live metrics for MiddlewareServer[EAP|Wildfly] instances

---

app/models/manageiq/providers/hawkular/middleware_manager.rb

This fix the cert store if it's not created before call the validation method, create the endpoint and assign the certificate_authority
Related with : https://github.com/ManageIQ/manageiq-providers-hawkular/pull/100
Related with: UI https://github.com/ManageIQ/manageiq-ui-classic/pull/2577
Related with: UI https://github.com/ManageIQ/manageiq-ui-classic/pull/2660
cc @tumido , @israel-hdez

Create cert_store if it's not created before validation

---

app/models/manageiq/providers/hawkular/inventory/operation_notification.rb
app/models/manageiq/providers/hawkular/inventory/server_operations.rb
app/models/manageiq/providers/hawkular/middleware_manager.rb
spec/models/manageiq/providers/hawkular/middleware_manager_spec.rb

This PR rewrites the MW datasource removal operation, so it is run against MW datasource (because it's called from MW datasource controller, not the MW server one). It ensures proper `Notification` is posted, and also fixes the notification handling for MW deployment (because solution to this problem fixes that as well)
Additional fix enhancement to #111's issue [~~BUG 1515285~~](https://bugzilla.redhat.com/show_bug.cgi?id=1515285)
Fixes [BUG 1518292](https://bugzilla.redhat.com/show_bug.cgi?id=1518292)

Fix RemoveDatasource operation notification

---

app/models/manageiq/providers/hawkular/middleware_manager/event_catcher/runner.rb

There's one more place we require events to be specified in order to show up on the Timeline.
It might be worth thinking about getting rid of this `@whitelist` here, since we define the same events in `settings.yml` as well.
Fixes: [BUG 1515476](https://bugzilla.redhat.com/show_bug.cgi?id=1515476)

Add JDBC events to Timeline

---

spec/models/manageiq/providers/hawkular/middleware_manager_spec.rb

https://github.com/ManageIQ/manageiq/pull/16729/files removed the
generation of middleware events which these tests are checking for so
the tests can be safely removed.

Fix failing middleware event tests
